name: herbal
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.17.0-266.1.beta <3.0.0"
dependencies:
  carousel_indicator: ^1.0.6
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  firebase_core: ^2.1.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_riverpod: ^2.1.1
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  go_router: ^5.1.5
  google_fonts: ^3.0.1
  ionicons: ^0.2.1
  lottie: ^2.0.0
  responsive_builder: ^0.4.3
  stacked: ^3.0.0
  video_player: ^2.4.7
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#2196f3"
    theme_color: "#2196f3"
dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    #   fonts:
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
